


// Generated by https://quicktype.io

export interface imageFormat_I {
    name: string;
    type: string;
    file: string;
    format: string;
    folder: string;
    src: string;
    _id?: string;
    details?: null;
    ownerRelation?: OwnerRelation_I;
    createdAt?: dateAt_I;
    updatedAt?: dateAt_I;
}

export interface dateAt_I {
    date: string;
    type: string;
    _id?: string;
}

export interface OwnerRelation_I {
    id_owner: string;
    schemaRelation: string;
    _id?: string;
}
