export enum _Configuration_Keys {
    JWT_SECRET = "JWT_SECRET",
    MONGODB = "MONGODB",
    PORT = "PORT",
    LOG_LEVEL = "LOG_LEVEL",
    ENVIROMENT = "ENVIROMENT",
    ALLOWEDORIGINS = "ALLOWEDORIGINS",
    EMAILTEST = "EMAILTEST",
    EMAILINFO = "EMAILINFO",
    DEFAULT_LIMIT = "DEFAULT_LIMIT",
}


